[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
# Internal crates referenced by member manifests via `*.workspace = true`.
mlx-internal-macros = { path = "crates/mlx-internal-macros" }
mlx-macros = { path = "crates/mlx-macros" }
mlx-sys = { path = "crates/mlx-sys" }

bindgen = "0.72.1"
bytemuck = "1"
cc = "1"
cmake = "0.1"
darling = "0.24"
dyn-clone = "1"
float_eq = "1"
half = "2"
itertools = "0.15"
libc = "0.2"
mach-sys = "0.5"
num-complex = "0.4"
num-traits = "0.2"
num_enum = "0.7"
parking_lot = "0.12"
paste = "1"
pretty_assertions = "1.4.0"
proc-macro2 = "1"
quote = "1"
safetensors = "0.8"
smallvec = "1"
strum = { version = "0.28", features = ["derive"] }
syn = { version = "3", features = ["full"] }
tempfile = "3"
thiserror = "2"
