[doctor]
checks = [
  {check = "homebrew"},
  {check = "tool-versions", command = "plugin-installed", args = {plugin = "rust"}},
  {check = "tool-versions", command = "package-installed", args = {plugin = "rust"}},
  {check = "rust", command = "crate-installed", args = {name = ["cargo-audit","cargo-outdated", "cargo-nextest"]}},
  {check = "rust", command = "target-installed", args = {target = ["aarch64-apple-darwin"]}},
  {name = "Metal toolchain present", shell = "xcrun metal --version >/dev/null 2>&1", remedy = "xcodebuild -downloadComponent MetalToolchain"},
]

[test]
checks = [
  {name = "rust: test!", shell = "cargo nextest run --color always", verbose = true},
  {name = "Check for warnings", shell = "cargo check --color always"},
]

[audit]
checks = [
  {check = "rust", command = "audit", verbose = true},
  {name = "rust: check", shell = "cargo check", remedy = "cargo fix --allow-dirty"},
  {name = "rust: clippy", shell = "cargo clippy --all-targets -- -D warnings", remedy = "cargo clippy --fix --allow-dirty"},
  {check = "rust", command = "format-check"},
]

[outdated]
checks = [
  {check = "rust"},
]

[update]
steps = [
  {step = "git", command = "pull"},
  {doctor = {}},
]

[shipit]
steps = [
  {audit = {}},
  {update = {}},
  {test = {}},
  {step = "git", command = "push"},
]

